name: verificationsystem
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_picker: ^2.0.20
  pinput: ^3.0.1
  image_picker: ^0.8.4       
  cached_network_image: ^3.0.0
  flutter_svg: ^2.0.5
  smooth_page_indicator: ^1.1.0
  dotted_border: ^2.1.0
  google_fonts: ^2.0.0

  firebase_core: ^2.23.0
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.1
  firebase_storage: ^11.5.4
  firebase_app_check: ^0.2.1+8
  path: ^1.8.2
  #provider: ^5.0.0
  #firebase_messaging

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
   - assets/images/

 