// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqgcf8dmK-AHgPNZz4YeWUNwplPSiNwHI',
    appId: '1:600175299859:web:42cdf8a322e8c92e1adee6',
    messagingSenderId: '600175299859',
    projectId: 'verificationsystem-622a5',
    authDomain: 'verificationsystem-622a5.firebaseapp.com',
    storageBucket: 'verificationsystem-622a5.appspot.com',
    measurementId: 'G-E0ZWTWP32Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIw7_HuTGJdjk69tIR2T5MDex4zXLPGD0',
    appId: '1:600175299859:android:3993721b107524441adee6',
    messagingSenderId: '600175299859',
    projectId: 'verificationsystem-622a5',
    storageBucket: 'verificationsystem-622a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXcfDymo8AYI0r4e1JqRmd6lq7_z5xkE',
    appId: '1:600175299859:ios:1b0ef6c749fb550d1adee6',
    messagingSenderId: '600175299859',
    projectId: 'verificationsystem-622a5',
    storageBucket: 'verificationsystem-622a5.appspot.com',
    iosBundleId: 'com.example.verificationsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXcfDymo8AYI0r4e1JqRmd6lq7_z5xkE',
    appId: '1:600175299859:ios:1b0ef6c749fb550d1adee6',
    messagingSenderId: '600175299859',
    projectId: 'verificationsystem-622a5',
    storageBucket: 'verificationsystem-622a5.appspot.com',
    iosBundleId: 'com.example.verificationsystem',
  );
}
